[package]
name = "breakout"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["wav"] }

# Enable fast compiles in dev mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
